#include "compiler/constants.h"
#include "compiler/ast.h"

namespace yalx::cpl {

    const char *Constants::kPrimitiveTypeClassNames[] = {
            nullptr,        //    V(unit)
            kAnyClassName,  //    V(any)
            "Bool",         //    V(bool)
            "Char",         //    V(char)
            "I8",           //    V(i8)
            "U8", //    V(u8)
            "I16", //    V(i16)
            "U16", //    V(u16)
            "I32", //    V(i32)
            "U32", //    V(u32)
            "I64", //    V(i64)
            "U64", //    V(u64)
            "F32", //    V(f32)
            "F64", //    V(f64)
            "String", //    V(string)
            nullptr, //    V(channel)
            nullptr, //    V(array)
            nullptr, //    V(class)
            nullptr, //    V(struct)
            nullptr, //    V(interface)
            nullptr, //    V(function)
            nullptr, //    V(symbol)
    };

    constexpr static Type::Primary kErrTag = Type::kMaxTypes;

#define PREIFX_PADDING  kErrTag, kErrTag, kErrTag, kErrTag
#define POSTFIX_PADDING kErrTag, kErrTag, kErrTag, kErrTag, kErrTag, kErrTag, kErrTag, kErrTag, kErrTag, kErrTag, kErrTag
#define ALL_PADDING     PREIFX_PADDING, \
                        kErrTag, kErrTag, kErrTag, kErrTag, kErrTag, kErrTag, kErrTag, kErrTag, kErrTag, kErrTag, \
                        POSTFIX_PADDING
#define D(name)         Type::kType_##name


    static const Type::Primary kTypeReducingRules[Type::kMaxTypes][Type::kMaxTypes] = {
            /* x */    {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
            /* i8 */
                       {PREIFX_PADDING, D(i8),  D(u8),  D(i16), D(u16), D(i32), D(u32), D(i64), D(u64), D(f32), D(f64), POSTFIX_PADDING},
            /* u8 */
                       {PREIFX_PADDING, D(u8),  D(u8),  D(i16), D(u16), D(i32), D(u32), D(i64), D(u64), D(f32), D(f64), POSTFIX_PADDING},
            /* i16 */
                       {PREIFX_PADDING, D(i16), D(i16), D(i16), D(u16), D(i32), D(u32), D(i64), D(u64), D(f32), D(f64), POSTFIX_PADDING},
            /* u16 */
                       {PREIFX_PADDING, D(u16), D(u16), D(u16), D(u16), D(i32), D(u32), D(i64), D(u64), D(f32), D(f64), POSTFIX_PADDING},
            /* i32 */
                       {PREIFX_PADDING, D(i32), D(i32), D(i32), D(i32), D(i32), D(u32), D(i64), D(u64), D(f32), D(f64), POSTFIX_PADDING},
            /* u32 */
                       {PREIFX_PADDING, D(u32), D(u32), D(u32), D(u32), D(u32), D(u32), D(i64), D(u64), D(f32), D(f64), POSTFIX_PADDING},
            /* i64 */
                       {PREIFX_PADDING, D(i64), D(i64), D(i64), D(i64), D(i64), D(i64), D(i64), D(u64), D(f32), D(f64), POSTFIX_PADDING},
            /* u64 */
                       {PREIFX_PADDING, D(u64), D(u64), D(u64), D(u64), D(u64), D(u64), D(u64), D(u64), D(f32), D(f64), POSTFIX_PADDING},
            /* f32 */
                       {PREIFX_PADDING, D(f32), D(f32), D(f32), D(f32), D(f32), D(f32), D(f32), D(f32), D(f32), D(f64), POSTFIX_PADDING},
            /* f64 */
                       {PREIFX_PADDING, D(f64), D(f64), D(f64), D(f64), D(f64), D(f64), D(f64), D(f64), D(f64), D(f64), POSTFIX_PADDING},
            /* x */
                       {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
            /* x */
                       {ALL_PADDING},
    };

#undef ALL_PADDING
#undef D
#undef PREIFX_PADDING
#undef POSTFIX_PADDING


    int Constants::ReduceNumberType(int lhs, int rhs) {
        assert(lhs >= 0 && lhs < Type::kMaxTypes);
        assert(rhs >= 0 && rhs < Type::kMaxTypes);
        Type::Primary rv = static_cast<Type::Primary>(kTypeReducingRules[lhs][rhs]);
        assert(rv != Type::kMaxTypes);
        return rv;
    }

#define D(name)         CastingRule::name

    static const CastingRule kTypeCastingRules[Type::kMaxTypes][Type::kMaxTypes] = {
            /* unit */ {
                               /* unit */ D(ALLOW),
                               /* any */  D(DENY),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* any */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(ALLOW_UNBOX),
                               /* char */ D(ALLOW_UNBOX),
                               /* i8 */   D(ALLOW_UNBOX),
                               /* u8 */   D(ALLOW_UNBOX),
                               /* i16 */  D(ALLOW_UNBOX),
                               /* u16 */  D(ALLOW_UNBOX),
                               /* i32 */  D(ALLOW_UNBOX),
                               /* u32 */  D(ALLOW_UNBOX),
                               /* i64 */  D(ALLOW_UNBOX),
                               /* u64 */  D(ALLOW_UNBOX),
                               /* f32 */  D(ALLOW_UNBOX),
                               /* f64 */  D(ALLOW_UNBOX),
                               /* string */    D(ALLOW_TYPING),
                               /* channel */   D(ALLOW_TYPING),
                               /* array */     D(ALLOW_TYPING),
                               /* class */     D(ALLOW_TYPING),
                               /* struct */    D(ALLOW_UNBOX),
                               /* enum */      D(DENY),
                               /* option */    D(ALLOW_TYPING),
                               /* interface */ D(ALLOW_TYPING_CONCEPT),
                               /* function */  D(ALLOW_TYPING),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* bool */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(ALLOW),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* char */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(ALLOW),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(ALLOW),
                               /* u32 */  D(ALLOW),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* i8 */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(ALLOW),
                               /* u8 */   D(ALLOW),
                               /* i16 */  D(ALLOW),
                               /* u16 */  D(ALLOW),
                               /* i32 */  D(ALLOW),
                               /* u32 */  D(ALLOW),
                               /* i64 */  D(ALLOW),
                               /* u64 */  D(ALLOW),
                               /* f32 */  D(ALLOW),
                               /* f64 */  D(ALLOW),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* u8 */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(ALLOW),
                               /* u8 */   D(ALLOW),
                               /* i16 */  D(ALLOW),
                               /* u16 */  D(ALLOW),
                               /* i32 */  D(ALLOW),
                               /* u32 */  D(ALLOW),
                               /* i64 */  D(ALLOW),
                               /* u64 */  D(ALLOW),
                               /* f32 */  D(ALLOW),
                               /* f64 */  D(ALLOW),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* i16 */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(ALLOW),
                               /* u8 */   D(ALLOW),
                               /* i16 */  D(ALLOW),
                               /* u16 */  D(ALLOW),
                               /* i32 */  D(ALLOW),
                               /* u32 */  D(ALLOW),
                               /* i64 */  D(ALLOW),
                               /* u64 */  D(ALLOW),
                               /* f32 */  D(ALLOW),
                               /* f64 */  D(ALLOW),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* u16 */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(ALLOW),
                               /* u8 */   D(ALLOW),
                               /* i16 */  D(ALLOW),
                               /* u16 */  D(ALLOW),
                               /* i32 */  D(ALLOW),
                               /* u32 */  D(ALLOW),
                               /* i64 */  D(ALLOW),
                               /* u64 */  D(ALLOW),
                               /* f32 */  D(ALLOW),
                               /* f64 */  D(ALLOW),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* i32 */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(ALLOW),
                               /* u8 */   D(ALLOW),
                               /* i16 */  D(ALLOW),
                               /* u16 */  D(ALLOW),
                               /* i32 */  D(ALLOW),
                               /* u32 */  D(ALLOW),
                               /* i64 */  D(ALLOW),
                               /* u64 */  D(ALLOW),
                               /* f32 */  D(ALLOW),
                               /* f64 */  D(ALLOW),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* u32 */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(ALLOW),
                               /* u8 */   D(ALLOW),
                               /* i16 */  D(ALLOW),
                               /* u16 */  D(ALLOW),
                               /* i32 */  D(ALLOW),
                               /* u32 */  D(ALLOW),
                               /* i64 */  D(ALLOW),
                               /* u64 */  D(ALLOW),
                               /* f32 */  D(ALLOW),
                               /* f64 */  D(ALLOW),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* i64 */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(ALLOW),
                               /* u8 */   D(ALLOW),
                               /* i16 */  D(ALLOW),
                               /* u16 */  D(ALLOW),
                               /* i32 */  D(ALLOW),
                               /* u32 */  D(ALLOW),
                               /* i64 */  D(ALLOW),
                               /* u64 */  D(ALLOW),
                               /* f32 */  D(ALLOW),
                               /* f64 */  D(ALLOW),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* u64 */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(ALLOW),
                               /* u8 */   D(ALLOW),
                               /* i16 */  D(ALLOW),
                               /* u16 */  D(ALLOW),
                               /* i32 */  D(ALLOW),
                               /* u32 */  D(ALLOW),
                               /* i64 */  D(ALLOW),
                               /* u64 */  D(ALLOW),
                               /* f32 */  D(ALLOW),
                               /* f64 */  D(ALLOW),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* f32 */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(ALLOW),
                               /* u8 */   D(ALLOW),
                               /* i16 */  D(ALLOW),
                               /* u16 */  D(ALLOW),
                               /* i32 */  D(ALLOW),
                               /* u32 */  D(ALLOW),
                               /* i64 */  D(ALLOW),
                               /* u64 */  D(ALLOW),
                               /* f32 */  D(ALLOW),
                               /* f64 */  D(ALLOW),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* f64 */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(ALLOW),
                               /* u8 */   D(ALLOW),
                               /* i16 */  D(ALLOW),
                               /* u16 */  D(ALLOW),
                               /* i32 */  D(ALLOW),
                               /* u32 */  D(ALLOW),
                               /* i64 */  D(ALLOW),
                               /* u64 */  D(ALLOW),
                               /* f32 */  D(ALLOW),
                               /* f64 */  D(ALLOW),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* string */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(ALLOW),
                               /* channel */   D(DENY),
                               /* array */     D(I8_U8_CHAR_ARRAY_ONLY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* channel */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(DENY),
                               /* channel */   D(ELEMENT_IN_OUT),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* array */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(I8_U8_CHAR_ARRAY_ONLY),
                               /* channel */   D(DENY),
                               /* array */     D(ELEMENT),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* class */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(CLASS_BASE_OF),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(CONCEPT),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* struct */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(CHILD_CLASS_ONLY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* enum */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(DENY),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(ALLOW),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* option */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(ALLOW_OPTION_TEST),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(OPTION_VALUE),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* interface */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(CONCEPT),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(SELF_ONLY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* function */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(ALLOW),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(PROTOTYPE),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* none */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(DENY),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(ALLOW),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
            /* symbol */
                       {
                               /* unit */ D(DENY),
                               /* any */  D(DENY),
                               /* bool */ D(DENY),
                               /* char */ D(DENY),
                               /* i8 */   D(DENY),
                               /* u8 */   D(DENY),
                               /* i16 */  D(DENY),
                               /* u16 */  D(DENY),
                               /* i32 */  D(DENY),
                               /* u32 */  D(DENY),
                               /* i64 */  D(DENY),
                               /* u64 */  D(DENY),
                               /* f32 */  D(DENY),
                               /* f64 */  D(DENY),
                               /* string */    D(DENY),
                               /* channel */   D(DENY),
                               /* array */     D(DENY),
                               /* class */     D(DENY),
                               /* struct */    D(DENY),
                               /* enum */      D(DENY),
                               /* option */    D(DENY),
                               /* interface */ D(DENY),
                               /* function */  D(DENY),
                               /* none */      D(DENY),
                               /* symbol */    D(DENY),
                       },
    };

#undef D

    CastingRule Constants::HowToCasting(int dest, int src) {
        assert(dest >= 0 && dest < Type::kMaxTypes);
        assert(src >= 0 && src < Type::kMaxTypes);
        return kTypeCastingRules[src][dest];
    }

} // namespace yalx
